# fly.toml app configuration file generated for fso-notes-app-part3b on 2023-06-05T15:01:27+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fso-notes-app-part3b"
primary_region = "sin"

[env]
PORT = "8080"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
